### ISSUE TITLE
Tool only selecting 10-20 pictures at a time

### ISSUE THREAD

**Issue by taugusti** [mrishab/google-photos-delete-tool#1]
Hi,
Great tool!
Too bad we need it... Google should really implement a proper delete tool in the app it self...

But... the tool takes forever if you have many pictures... 7 seconds per round means ~7000 pictures per hour (15 pic/round average).

It would be really great if the tool could select perhaps 500 pcs per cycle...

/th

**Comment by taugusti** [comment]
Ahhh... I just realized that if I zoom out in the browser, the number grows sigificantly!!!
at 25% I get ~180 pic/round - much better!
/th

**Comment by andrevr** [comment]
Was about to add this as a hack/tip. Gratefully, GitHub caught me and pointed me here :)
