### ISSUE TITLE
Delete only a certain amount

### ISSUE THREAD

**Issue by l-ika-l** [mrishab/google-photos-delete-tool#11]
It'd be cool if you could set the script to only delete a certain amount of photos instead of all

**Comment by mrishab** [comment]
Hi @l-ika-l , I added the support for deleting N number of photos as you asked.
The code change is here: https://github.com/mrishab/google-photos-delete-tool/commit/cbdf7a22db1b4c2bdf3141ee4e69462d6cc72ab4

See _note_ under the step 5 of the document to understand how to use it.

**Comment by l-ika-l** [comment]
thanks
