### ISSUE TITLE
This works brilliantly for my case, thanks a lot for this script! ＼(＾O＾)／

### ISSUE THREAD

**Issue by vgrange** [mrishab/google-photos-delete-tool#12]
FTR using latest Chrome on MacOS Mojave.

**Comment by vusonhust** [comment]
This worked for me too. Chrome 79.0.3945.130 on Macos Catalina tested.

**Comment by mrishab** [comment]
Thanks! Appreciate the feedback.

**Comment by BitProcessor** [comment]
Perfect tool! Thanks a lot 🥇
