### ISSUE TITLE
"No More Photos Left To Delete"

### ISSUE THREAD

**Issue by grravity** [mrishab/google-photos-delete-tool#13]
I have like 40k photos, it went through about 200 (in selection bulks of about 25) then stopped and said there are no more photos to delete.

**Comment by Z3ROGRAV1TYx** [comment]
Also if I try rerunning it (tried on chrome and firefox) it just selects photos, opens the move to trash dialog then unselects everything. Photos aren't getting deleted. Manually doing it works, but I can't do this manually for 40k photos..

**Comment by mrishab** [comment]
Hi, can you share your console messages? Is there any error or something?
Also, you can edit the script and put the word `debugger` to pause the script. Seems like you're having the problem where script is not able to find the 'delete/confirm button'

**Comment by grravity** [comment]
@mrishab As this is almost 3 months old, I had spent so much time going through and manually deleting the photos.
So can't do this, sorry
