### ISSUE TITLE
It did not helped

### ISSUE THREAD

**Issue by mauditt** [mrishab/google-photos-delete-tool#14]
Hi, this script did not helped for me. Chrome version 80.0.3987.163 , no photo was deleted. Why ??
I attached one file - do you see a bug ? Where is the problem ?
![screen](https://user-images.githubusercontent.com/52030580/78592217-07f82180-7845-11ea-9d8f-62ce1aacea1e.jpg)

**Comment by mrishab** [comment]
Hi, could you try again without setting the UI as mobile?

**Comment by Pietjepukspam** [comment]
I have the same problem. Version 80 and 81 both don't work. Language of the browser is set to us English. Please help :)

**Comment by Pietjepukspam** [comment]
> I have the same problem. Version 80 and 81 both don't work. Language of the browser is set to us English. Please help :)

works now, it wasnt about my chrome language but google language preference!

**Comment by mrishab** [comment]
Thanks for confirming.
Would you be interested in creating a PR to update the:
[FAQ](https://github.com/mrishab/google-photos-delete-tool#faqs) section with your findings?
