### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by sirber** [mrishab/google-photos-delete-tool#16]
I added the code in a snipet.
I see the photos get selected, then they get unselected. They get selected again, etc.

**Comment by sirber** [comment]
same thing in the console. my locale in photos is in french, is that a problem?

**Comment by sirber** [comment]
works only in english :)

**Comment by mrishab** [comment]
Hi @sirber, this is a known issue. Currently, you can change your language to English and the script should work with it.
See FAQ: https://github.com/mrishab/google-photos-delete-tool#faqs
