### ISSUE TITLE
How to restart tool

### ISSUE THREAD

**Issue by raybooysen** [mrishab/google-photos-delete-tool#19]
Can we add instructions on how to restart the tool?  If there is a slowdown to loading the next set of photos, the tool logs that is has exited.

But how can I restart manually other than doing a full reload and pasting the script?

Thanks!

**Comment by mrishab** [comment]
See: https://github.com/mrishab/google-photos-delete-tool/commit/bb766e47fc5261e1c1b8077209189321baa9e058
Added instructions in FAQ. You don't need to reload the page.

**Comment by raybooysen** [comment]
Thank you!
