### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by kylehotchkiss** [mrishab/google-photos-delete-tool#31]
Sorry to make an issue to do this, but not sure another way to get in touch. Trying to leave Google Photos is such a pain and your solution here helps automate a mundane task wonderfully. **Thank you** for giving me a way to exit Google Photos and all the privacy ramifications of keeping entire libraries on their servers. Take Care!

**Comment by koehhian** [comment]
Hey, I wanna say the same. I'd been googling the solution, til I found this project today. Thank you so much.

**Comment by seltzered** [comment]
Worked for me, thanks! Had to run it a few times but did the job.

**Comment by mameaw14** [comment]
Thank you! I use this to get rid of more than 150GB of photos. Couldn't be easy without this.

**Comment by lolmaus** [comment]
Thank you! Google funked me over and won't let me pay for cloud storage space. I needed to delete many thousands of photos to unblock my email.

:heart:

**Comment by rommeswi** [comment]
Great script, thank you!

**Comment by josy1024** [comment]
Thank You! - Works with default Parameters.

**Comment by PinkPanther901** [comment]
Thank you so much for this script. It's absolute BS that Google doesn't provide a "Delete All" option (but they sure do make it easy to upload everything without thinking about it!)

**Comment by mrishab** [comment]
Thank you everyone!
