### ISSUE TITLE
Zoom out --> selects more photos at once

### ISSUE THREAD

**Issue by Cervenka** [mrishab/google-photos-delete-tool#41]
FYI:

When I first ran the script it would delete 35 photos at once.
I then zoomed out (Command + Minus) which resulted in over 800 images being deleted at once.

That might be of interest for the guide.

Thank you for providing your script.

**Comment by NeoHBz** [comment]
thanks a lot, deleted around 4k+ photos in minutes 🎉

**Comment by simplenotezy** [comment]
thanks

**Comment by simplenotezy** [comment]
Unbelievable google makes it this hard.

**Comment by mrishab** [comment]
Thats an amazing suggestion!! I'll see if I get around to adding it to the readme. But if u get time could you make a PR?

**Comment by XargsUK** [comment]
Discovered the same thing myself after I moved the window to a smaller screen and it was deleting half the amount. Please could we merge this PR @mrishab <3
