### ISSUE TITLE
Not an issue. Just thanks!

### ISSUE THREAD

**Issue by soldius** [mrishab/google-photos-delete-tool#58]
Holy crap dude. Thank you so much for this. I was really hating manually deleting my thousands of photos manually, You're a lifesaver! Thank you so much!!!

**Comment by tekfranz** [comment]
I also want to tag on here and say thank you for a fantastic tool!

**Comment by coolarj10** [comment]
Woohoo thank you!!! 45GB of photos deleted!!! I had to re-run the script several times over the course of a day or two because of random errors or something that would cause it to stop working. But ultimately it worked, what a blessing. Thanks so much!!

**Comment by Sonixier** [comment]
```
[INFO] No more images to delete.
[SUCCESS] Tool exited.
```
Thank you for this script!

**Comment by jasonpatrickellykrause** [comment]
W00t!

**Comment by modkeyIT** [comment]
450GB of photos deleted.  Wish I found you last time I had to do this.  Amazing work thank you!

**Comment by mrishab** [comment]
Thank you everyone!!
