### ISSUE TITLE
There is now an extension to delete all google photos

### ISSUE THREAD

**Issue by Glench** [mrishab/google-photos-delete-tool#59]
Hi! Just wanted to let the author and others know about an extension I made that lets you bulk delete all google photos automatically without needing to paste in any code! Here's the link: https://chromewebstore.google.com/detail/delete-all-google-photos/bebhhjmapjadpdkkhbkpnpbjhkhndofl?hl=en

**Comment by kdorland** [comment]
I have to pay to delete more than 200 photos? Get lost...

**Comment by Glench** [comment]
Deleting 200 photos per day is free, yep! If you look at the reviews lots of people have found it worthwhile since it frees up your storage space and is just a small one-time payment for lifetime access. 

![Screenshot 2024-01-17 at 3 24 50 PM](https://github.com/mrishab/google-photos-delete-tool/assets/451461/7864b302-a7b2-47e4-8e5f-d851180a9419)

But obviously not everyone feels like it's worth it, so you can use other solutions if you like :) Or if the cost represents a financial hardship I'd be happy to offer the extension at a discount or free! Just drop me a line. Cheers!

**Comment by chipbite** [comment]
This thread is an ad.
