### ISSUE TITLE
Problems with the script

### ISSUE THREAD

**Issue by christophebirkeland** [mrishab/google-photos-delete-tool#8]
I get the following message repeatedly:
[INFO] Deleting 29 images debugger eval code:36:13
[INFO] Deleting 29 images debugger eval code:36:13
[INFO] Deleting 29 images debugger eval code:36:13

and the script actually never deletes any images. It marks images, but does not delete them.

Any help?

PS: I have tried it on both OSX and win10, firefox and chrome (latest versions). Same results. I need to delete approximately 200,000 images...

**Comment by mrishab** [comment]
@christophebirkeland What's the language set for your browser or google photos.
This script is currently meant to work for English only.

Another reason, this could be happening is because of the `confirmationButton not working` bug we had. **If so, it has been fixed now. Please try again.**
