### ISSUE TITLE
If it just checks and unchecks photos..

### ISSUE THREAD

**Issue by sh4dowb** [mrishab/google-photos-delete-tool#9]
replace this:
`deleteButton: 'button[title="Delete"]',`

with your language. hover on delete button to see the translation. it doesn't work if your account isn't in English language

if it doesn't click confirmation button, there's pull requests for that

**Comment by donjuanmon** [comment]
The following script worked for me:

```
// Selector for Images and buttons
const ELEMENT_SELECTORS = {
    checkboxClass: '.ckGgle',
    deleteButton: 'button[title="Delete"]',
    confirmationButton: '#yDmH0d > div.llhEMd.iWO5td > div > div.g3VIld.V639qd.bvQPzd.oEOLpc.Up8vH.J9Nfi.A9Uzve.iWO5td > div.XfpsVe.J9fJmf > button.VfPpkd-LgbsSe.VfPpkd-LgbsSe-OWXEXe-k8QpJ.nCP5yc.kHssdc.HvOprf'
}

// Time Configuration (in milliseconds)
const TIME_CONFIG = {
    delete_cycle: 7000,
    press_button_delay: 1000
};

let imageCount = 0;

let checkboxes;
let buttons = {
    deleteButton: null,
    confirmationButton: null
}

let deleteTask = setInterval(() => {

    checkboxes = document.querySelectorAll(ELEMENT_SELECTORS['checkboxClass']);

    if (checkboxes.length <= 0) {
        console.log("[INFO] No more images to delete.");
        clearInterval(deleteTask);
        console.log("[SUCCESS] Tool exited.");
        return;
    }

    imageCount += checkboxes.length;

    checkboxes.forEach((checkbox) => { checkbox.click() });
    console.log("[INFO] Deleting", checkboxes.length, "images");

    setTimeout(() => {

        buttons.deleteButton = document.querySelector(ELEMENT_SELECTORS['deleteButton']);
        buttons.deleteButton.click();

        setTimeout(() => {
            buttons.confirmation_button = document.querySelector(ELEMENT_SELECTORS['confirmationButton']);
            buttons.confirmation_button.click();
        }, TIME_CONFIG['press_button_delay']);
    }, TIME_CONFIG['press_button_delay']);
}, TIME_CONFIG['delete_cycle']);
```

**Comment by varnav** [comment]
Doesn't work for me :(

**Comment by donjuanmon** [comment]
> Doesn't work for me :(

Try running the above command in Firefox, it didn't work in Chrome for whatever reason

**Comment by varnav** [comment]
No, just selects and deselects in Firefox as well.
I have Russian language set.
Anything I can help to diagnose this?

**Comment by donjuanmon** [comment]
> No, just selects and deselects in Firefox as well.
> I have Russian language set.
> Anything I can help to diagnose this?

Set language to English and try again.

**Comment by varnav** [comment]
Works with English. How can we fix it then?

**Comment by mrishab** [comment]
@donjuanmon Could you make a PR with your version of the script so that we can make the fix available to everyone?

**Comment by konstantinj** [comment]
fyi, for me the current version with

```
confirmationButton: '#yDmH0d > div.llhEMd.iWO5td > div > div.g3VIld.V639qd.bvQPzd.oEOLpc.Up8vH.J9Nfi.A9Uzve.iWO5td > div.XfpsVe.J9fJmf > button.VfPpkd-LgbsSe.VfPpkd-LgbsSe-OWXEXe-k8QpJ.nCP5yc.kHssdc.HvOprf'
```

works. My language defaults to german so I've changes title to "Löschen" and it works.

**Comment by robertboyl** [comment]
pitty I found this here just now :) I spent some time figuring out it wasnt working due to language not being set to english.

Pls add some comment on the readme about this.

Easy solution: set your google account to US english, then it works.

Thanks a lot for script!!

**Comment by mrishab** [comment]
Hi there, I added this information to the README: https://github.com/mrishab/google-photos-delete-tool/commit/6f0cb5a9d1894a13789910c82f3b3a9501fc5233

Also, I created an FAQ section and invite everyone to contribute to it when they find solutions to issues, thanks.
